#!/usr/bin/env bash
set -euo pipefail

API_BASE_URL="${API_BASE_URL:-}"
ASSET_BASE_URL="${ASSET_BASE_URL:-$API_BASE_URL}"
FRONTEND_BASE_URL="${FRONTEND_BASE_URL:-}"

cat > public/js/runtime-config.js <<EOF
(function initRuntimeConfig(global) {
  // Generated by Jenkins at deploy time.
  global.__APP_CONFIG__ = {
    API_BASE_URL: "${API_BASE_URL}",
    ASSET_BASE_URL: "${ASSET_BASE_URL}",
    FRONTEND_BASE_URL: "${FRONTEND_BASE_URL}",
  };
})(window);
EOF

echo "runtime-config.js generated."

